# Generated by Django 3.0.3 on 2020-04-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='department',
        ),
        migrations.AddField(
            model_name='registration',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appoint.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.SmallIntegerField(),
        ),
    ]
