# Generated by Django 3.0.3 on 2020-04-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_auto_20200420_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='afternoon_registration_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='morning_registration_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
