# Generated by Django 3.0.3 on 2020-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_auto_20200420_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.SmallIntegerField(max_length=1),
        ),
    ]
