# Generated by Django 3.0.3 on 2020-05-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_auto_20200516_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appoint.Department'),
        ),
    ]
