# Generated by Django 3.0.3 on 2020-05-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0007_schedule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appoint.Department'),
        ),
    ]
