# Generated by Django 3.0.3 on 2020-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0009_auto_20200516_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
