# Generated by Django 3.0.3 on 2020-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0010_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateField(null=True),
        ),
    ]
