# Generated by Django 3.0.3 on 2020-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200418_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='break_rule_times',
            field=models.SmallIntegerField(default=0),
        ),
    ]
